### ISSUE TITLE
URL Parse fails when password contains @ symbol

### ISSUE THREAD

**Issue by peritz** [ryanharrison554/pyovpn-as#1]

**Comment by peritz** [comment]
Solution is to URL encode the username and password

**Comment by ryanharrison554** [comment]
Closed as this was fixed with commit 3f68829ae7315caf10386dc253129633a8af4f6f

**Comment by ryanharrison554** [comment]
Solution is not to URL encode the username and password, as the username and password doesn't seem to be decoded by the Python server on the other side.

This was tested on an older version of OpenVPN Access Server, so I will test it on the most recent update to see if it works or not. If not I will raise an issue with the developers.
